In [1]:
# import pickle
import pandas as pd
import numpy as np
from tqdm import tqdm_notebook
import torch

In [ ]:
## MLP

In [19]:
x=np.random.randint(0,5,(100000,5000))
y=np.random.randint(0,5,(20,5000))
x_=torch.from_numpy(x)
y_=torch.from_numpy(y)
# print(x)
# print(x_)

In [30]:
%%time
x.dot(y.T)

Wall time: 3.79 s


array([[19850, 19463, 20152, ..., 19810, 20163, 19665],
       [19446, 19349, 19842, ..., 19296, 19855, 19209],
       [20515, 20083, 20471, ..., 20112, 20519, 20160],
       ...,
       [19415, 19233, 19348, ..., 19314, 19550, 19348],
       [19841, 19371, 20035, ..., 19755, 20315, 19802],
       [20065, 19710, 20124, ..., 19679, 20069, 19761]])

In [35]:
%%time
np.einsum("ik,jk->ij",x,y)

Wall time: 2.74 s


array([[19850, 19463, 20152, ..., 19810, 20163, 19665],
       [19446, 19349, 19842, ..., 19296, 19855, 19209],
       [20515, 20083, 20471, ..., 20112, 20519, 20160],
       ...,
       [19415, 19233, 19348, ..., 19314, 19550, 19348],
       [19841, 19371, 20035, ..., 19755, 20315, 19802],
       [20065, 19710, 20124, ..., 19679, 20069, 19761]])

In [34]:
%%time
torch.matmul(x_,y_.t())

Wall time: 2.27 s


tensor([[19850, 19463, 20152,  ..., 19810, 20163, 19665],
        [19446, 19349, 19842,  ..., 19296, 19855, 19209],
        [20515, 20083, 20471,  ..., 20112, 20519, 20160],
        ...,
        [19415, 19233, 19348,  ..., 19314, 19550, 19348],
        [19841, 19371, 20035,  ..., 19755, 20315, 19802],
        [20065, 19710, 20124,  ..., 19679, 20069, 19761]], dtype=torch.int32)

Wall time: 2.17 s


tensor([[19850, 19463, 20152,  ..., 19810, 20163, 19665],
        [19446, 19349, 19842,  ..., 19296, 19855, 19209],
        [20515, 20083, 20471,  ..., 20112, 20519, 20160],
        ...,
        [19415, 19233, 19348,  ..., 19314, 19550, 19348],
        [19841, 19371, 20035,  ..., 19755, 20315, 19802],
        [20065, 19710, 20124,  ..., 19679, 20069, 19761]], dtype=torch.int32)

In [153]:
## 

RuntimeError: dot: Expected 1-D argument self, but got 2-D

In [32]:
# x=np.random.randint(0,2,(10800,5000))
# y=np.random.randint(0,2,(10800,5000))
x=np.random.rand(20800,5000)
y=np.random.rand(20800,5000)
x_=torch.from_numpy(x)
y_=torch.from_numpy(y)

In [35]:
%%timeit
torch.sum(x_*x_)

383 ms ± 4.13 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [36]:
%%timeit
torch.einsum("ij,ij->",x_,x_)

539 ms ± 18.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
