In [1]:
# import pickle
import pandas as pd
import numpy as np
from tqdm import tqdm_notebook
import torch

In [21]:
x=torch.tensor([1,2,3],requires_grad=True,dtype=torch.float32)

mask=torch.tensor([0,1,0],dtype=torch.uint8)
z=x.masked_fill(mask,0)*2
z.backward(torch.tensor([1.0,1.0,1.0]))
x.grad

tensor([2., 0., 2.])

In [49]:
x=torch.tensor([1,2,3,4],requires_grad=True,dtype=torch.float32)
y=x.max()
z=y*2
z.backward()
x.grad

tensor([0., 0., 0., 2.])

In [158]:
size=60
def criterionTriOrig(reduction="mean",size=None):
    def do(h0,h1,h2):
        h01=(h0*h1).sum(dim=1)
        h02=(h0*h2).sum(dim=1)
        Lt=torch.log(1+torch.exp(h02-h01))
        if reduction=="mean":
            assert size == None,"No need size"
            return {"Lt":Lt.mean()}
        if reduction=="max": 
            assert size ,"size isn't assigned yet"
            lossmax=torch.nn.functional.max_pool1d(Lt.view(1,1,Lt.size()[0]),kernel_size=size,stride=size).squeeze()
            assert lossmax.size()[0]==Lt.size()[0]/size,"Check if size is corrected"
            return {"Lt":lossmax.mean()}
    return do
class TriLossOri():
    def __init__(self,reduction="mean",size=None):
        self.reduction=reduction
        self.size=size
    def forward(self,h0,h1,h2):
        h01=(h0*h1).sum(dim=1)
        h02=(h0*h2).sum(dim=1)
        Lt=torch.log(1+torch.exp(h02-h01))
        if self.reduction=="mean":
            assert self.size == None,"No need size"
            return {"Lt":Lt.mean()}
        if self.reduction=="max": 
            assert self.size ,"size isn't assigned yet"
            lossmax=torch.nn.functional.max_pool1d(Lt.view(1,1,Lt.size()[0])
                                                   ,kernel_size=self.size,stride=self.size).squeeze()
            assert lossmax.size()[0]==Lt.size()[0]/self.size,"Check if size is corrected"
            return {"Lt":lossmax.mean()}
    def __call__(self,h0,h1,h2):
        return self.forward(h0,h1,h2)


h0=torch.rand(1080,100)
h1=torch.rand(1080,100)
h2=torch.rand(1080,100)
criterionTri=criterionTriOrig()
loss   =criterionTri(h0,h1,h2)["Lt"]
criterionTri=criterionTriOrig(reduction="max",size=60)
lossmax=criterionTri(h0,h1,h2)["Lt"]
print(loss,lossmax)
criterionTri=TriLossOri()
loss   =criterionTri(h0,h1,h2)["Lt"]
criterionTri=TriLossOri(reduction="max")
lossmax   =criterionTri(h0,h1,h2)["Lt"]
print(loss,lossmax)

tensor(1.2080) tensor(5.4012)


AssertionError: size isn't assigned yet

In [157]:
s="lOsQ"
s.upper()

'LOSQ'

In [140]:
lossmax

tensor(5.5739)

In [84]:
from BuildDataset import Tripletdataset
## Load industry dictionary
with open("D:4.AutoencoderForArticle.Mid-Industry/dict_guid_sparsebow_20000_single.v05.p","rb") as f:
    dict_guid_sparsebow_single= pickle.load(f)
with open("D:4.AutoencoderForArticle.Mid-Industry/dict_singleindustry_guid.p","rb") as f:
    dict_singleindustry_guid= pickle.load(f)

tensor([0.2734, 0.6865, 0.1541,  ..., 0.1351, 0.0864, 0.0310])

In [89]:
x=torch.tensor([2,1,3,4],requires_grad=True,dtype=torch.float32)
y=torch.nn.functional.max_pool1d(x.view(1,1,x.size()[0]),kernel_size=2,stride=2).squeeze()
z=y*2
z=z.mean()
z.backward()

In [90]:
x.grad

tensor([1., 0., 0., 1.])